title: Snow&Sky #博客标题
description: 小鳥の翼がついに大きくなって
keywords: blog,css,html,php #博客关键字
author: "Sky"

#title hide and show
hide: (つェ⊂)Sky~
show: ´∇｀Snow~ 

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "nishikinosky.github.io" # change this to the base hostname & protocol for your site

PJAX: true #启用PJAX，会与评论系统冲突（如不用评论系统建议开启）

paginate: 8 #同时显示的最大文章数，超过自动分页
paginate_path: "page:num"

background: img/miumiu.png
theme_color: 546E7A

# hydrogen-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
hydrogen-blog:
  date_format: "%b %-d, %Y"

#MathJax switch
MathJax: false

#install emoji
plugins:
  - jemoji

# social account
#image:
#twitter:Makiiii
  #username:@Makikikiii
#  site:
#facebook:
  #publisher: null
  #profile_id: null
  #app_id: null
  #authors: null
#  admins:

